export const Mock_table_data: any = [
  {
    name: 'Alice Johnson',
    salary: 75000,
    department: 'Engineering',
    email: 'alice.j@example.com',
    contact: '+1-555-123-4567',
  },
  {
    name: 'Bob Smith',
    salary: 62000,
    department: 'Marketing',
    email: 'bob.smith@example.com',
    contact: '+1-555-987-6543',
  },
  {
    name: 'Charlie Davis',
    salary: 95000,
    department: 'Engineering',
    email: 'charlie.d@example.com',
    contact: '+1-555-246-8013',
  },
  {
    name: 'Diana Miller',
    salary: 80000,
    department: 'Sales',
    email: 'diana.m@example.com',
    contact: '+1-555-111-2233',
  },
  {
    name: 'Ethan White',
    salary: 55000,
    department: 'Human Resources',
    email: 'e.white@example.com',
    contact: '+1-555-333-4455',
  },
  {
    name: 'Fiona Green',
    salary: 70000,
    department: 'Marketing',
    email: 'f.green@example.com',
    contact: '+1-555-555-6677',
  },
  {
    name: 'George Brown',
    salary: 110000,
    department: 'Engineering',
    email: 'george.b@example.com',
    contact: '+1-555-777-8899',
  },
  {
    name: 'Hannah Clark',
    salary: 68000,
    department: 'Sales',
    email: 'h.clark@example.com',
    contact: '+1-555-999-0011',
  },
  {
    name: 'Isaac Wilson',
    salary: 60000,
    department: 'Human Resources',
    email: 'isaac.w@example.com',
    contact: '+1-555-222-3344',
  },
  {
    name: 'Jane Taylor',
    salary: 85000,
    department: 'Sales',
    email: 'jane.t@example.com',
    contact: '+1-555-444-5566',
  },
];

export const MOCK_DATA = [
  {
    name: 'John Smith',
    email: 'john.smith@example.com',
    department: 'Engineering',
    designation: 'Software Developer',
    location: 'New York',
    reportingManager: 'Michael Brown',
    reportingManagerMail: 'michael.brown@example.com',
    joinedDate: '2023-01-15',
    experience: '2 yrs',
    currentlyWorking: 'yes',
    skills: 'Java, Spring Boot',
    personalDetails: 'Enjoys hiking',
  },
  {
    name: 'Emily Johnson',
    email: 'emily.johnson@example.com',
    department: 'Marketing',
    designation: 'Marketing Specialist',
    location: 'Chicago',
    reportingManager: 'Sarah Davis',
    reportingManagerMail: 'sarah.davis@example.com',
    joinedDate: '2022-06-10',
    experience: '3 yrs',
    currentlyWorking: 'yes',
    skills: 'SEO, Content Marketing',
    personalDetails: 'Loves photography',
  },
  {
    name: 'David Wilson',
    email: 'david.wilson@example.com',
    department: 'Finance',
    designation: 'Accountant',
    location: 'Los Angeles',
    reportingManager: 'Robert Taylor',
    reportingManagerMail: 'robert.taylor@example.com',
    joinedDate: '2021-03-20',
    experience: '4 yrs',
    currentlyWorking: 'yes',
    skills: 'Accounting, Excel',
    personalDetails: 'Enjoys reading',
  },
  {
    name: 'Sophia Martinez',
    email: 'sophia.martinez@example.com',
    department: 'HR',
    designation: 'HR Executive',
    location: 'Boston',
    reportingManager: 'Laura White',
    reportingManagerMail: 'laura.white@example.com',
    joinedDate: '2020-11-05',
    experience: '5 yrs',
    currentlyWorking: 'yes',
    skills: 'Recruitment, Employee Relations',
    personalDetails: 'Yoga enthusiast',
  },
  {
    name: 'James Anderson',
    email: 'james.anderson@example.com',
    department: 'Engineering',
    designation: 'Tech Lead',
    location: 'Seattle',
    reportingManager: 'Michael Brown',
    reportingManagerMail: 'michael.brown@example.com',
    joinedDate: '2019-09-15',
    experience: '8 yrs',
    currentlyWorking: 'yes',
    skills: 'Java, AWS, Docker',
    personalDetails: 'Fitness lover',
  },
  {
    name: 'Olivia Thomas',
    email: 'olivia.thomas@example.com',
    department: 'Design',
    designation: 'UI/UX Designer',
    location: 'San Francisco',
    reportingManager: 'Daniel Harris',
    reportingManagerMail: 'daniel.harris@example.com',
    joinedDate: '2022-02-18',
    experience: '3 yrs',
    currentlyWorking: 'yes',
    skills: 'Figma, Adobe XD',
    personalDetails: 'Art enthusiast',
  },
  {
    name: 'William Moore',
    email: 'william.moore@example.com',
    department: 'Support',
    designation: 'Support Engineer',
    location: 'Austin',
    reportingManager: 'Chris Clark',
    reportingManagerMail: 'chris.clark@example.com',
    joinedDate: '2021-08-12',
    experience: '4 yrs',
    currentlyWorking: 'yes',
    skills: 'Customer Support, Troubleshooting',
    personalDetails: 'Music lover',
  },
  {
    name: 'Isabella Taylor',
    email: 'isabella.taylor@example.com',
    department: 'QA',
    designation: 'QA Analyst',
    location: 'Denver',
    reportingManager: 'Robert Taylor',
    reportingManagerMail: 'robert.taylor@example.com',
    joinedDate: '2020-05-25',
    experience: '5 yrs',
    currentlyWorking: 'yes',
    skills: 'Manual Testing, Automation',
    personalDetails: 'Foodie',
  },
  {
    name: 'Benjamin Harris',
    email: 'benjamin.harris@example.com',
    department: 'Engineering',
    designation: 'Backend Developer',
    location: 'Miami',
    reportingManager: 'Michael Brown',
    reportingManagerMail: 'michael.brown@example.com',
    joinedDate: '2023-09-10',
    experience: '1 yr',
    currentlyWorking: 'yes',
    skills: 'Java, Spring Boot',
    personalDetails: 'Gamer',
  },
  {
    name: 'Charlotte Walker',
    email: 'charlotte.walker@example.com',
    department: 'Engineering',
    designation: 'Frontend Developer',
    location: 'Dallas',
    reportingManager: 'Michael Brown',
    reportingManagerMail: 'michael.brown@example.com',
    joinedDate: '2023-04-12',
    experience: '2 yrs',
    currentlyWorking: 'yes',
    skills: 'Angular, TypeScript',
    personalDetails: 'Travel enthusiast',
  },
];

export const BASIC_MOCK = [
  {
    id: 1,
    eid: 'a1f1c001-1111-4aaa-8aaa-111111111111',
    name: 'John Smith',
    currentlyWorking: 'yes',
    email: 'john.smith@example.com',
    salary: 850000,
  },
  {
    id: 2,
    eid: 'a1f1c002-2222-4bbb-8bbb-222222222222',
    name: 'Emily Johnson',
    currentlyWorking: 'yes',
    email: 'emily.johnson@example.com',
    salary: 920000,
  },
  {
    id: 3,
    eid: 'a1f1c003-3333-4ccc-8ccc-333333333333',
    name: 'Sophia Martinez',
    currentlyWorking: 'yes',
    email: 'sophia.martinez@example.com',
    salary: 780000,
  },
  {
    id: 4,
    eid: 'a1f1c004-4444-4ddd-8ddd-444444444444',
    name: 'James Anderson',
    currentlyWorking: 'no',
    email: 'james.anderson@example.com',
    salary: 450000,
  },
  {
    id: 5,
    eid: 'a1f1c005-5555-4eee-8eee-555555555555',
    name: 'Michael Brown',
    currentlyWorking: 'yes',
    email: 'michael.brown@example.com',
    salary: 990000,
  },
  {
    id: 6,
    eid: 'a1f1c006-6666-4fff-8fff-666666666666',
    name: 'Olivia Davis',
    currentlyWorking: 'yes',
    email: 'olivia.davis@example.com',
    salary: 870000,
  },
  {
    id: 7,
    eid: 'a1f1c007-7777-4aaa-8aaa-777777777777',
    name: 'William Miller',
    currentlyWorking: 'no',
    email: 'william.miller@example.com',
    salary: 510000,
  },
  {
    id: 8,
    eid: 'a1f1c008-8888-4bbb-8bbb-888888888888',
    name: 'Ava Wilson',
    currentlyWorking: 'yes',
    email: 'ava.wilson@example.com',
    salary: 760000,
  },
  {
    id: 9,
    eid: 'a1f1c009-9999-4ccc-8ccc-999999999999',
    name: 'Daniel Moore',
    currentlyWorking: 'yes',
    email: 'daniel.moore@example.com',
    salary: 830000,
  },
  {
    id: 10,
    eid: 'a1f1c010-aaaa-4ddd-8ddd-aaaaaaaaaaaa',
    name: 'Isabella Taylor',
    currentlyWorking: 'no',
    email: 'isabella.taylor@example.com',
    salary: 470000,
  },
  {
    id: 11,
    eid: 'a1f1c011-bbbb-4eee-8eee-bbbbbbbbbbbb',
    name: 'Ethan Thomas',
    currentlyWorking: 'yes',
    email: 'ethan.thomas@example.com',
    salary: 910000,
  },
  {
    id: 12,
    eid: 'a1f1c012-cccc-4fff-8fff-cccccccccccc',
    name: 'Mia Jackson',
    currentlyWorking: 'yes',
    email: 'mia.jackson@example.com',
    salary: 880000,
  },
  {
    id: 13,
    eid: 'a1f1c013-dddd-4aaa-8aaa-dddddddddddd',
    name: 'Alexander White',
    currentlyWorking: 'no',
    email: 'alexander.white@example.com',
    salary: 520000,
  },
  {
    id: 14,
    eid: 'a1f1c014-eeee-4bbb-8bbb-eeeeeeeeeeee',
    name: 'Charlotte Harris',
    currentlyWorking: 'yes',
    email: 'charlotte.harris@example.com',
    salary: 940000,
  },
  {
    id: 15,
    eid: 'a1f1c015-ffff-4ccc-8ccc-ffffffffffff',
    name: 'Benjamin Martin',
    currentlyWorking: 'yes',
    email: 'benjamin.martin@example.com',
    salary: 810000,
  },
  {
    id: 16,
    eid: 'a1f1c016-1212-4ddd-8ddd-121212121212',
    name: 'Amelia Thompson',
    currentlyWorking: 'yes',
    email: 'amelia.thompson@example.com',
    salary: 890000,
  },
  {
    id: 17,
    eid: 'a1f1c017-1313-4eee-8eee-131313131313',
    name: 'Henry Garcia',
    currentlyWorking: 'no',
    email: 'henry.garcia@example.com',
    salary: 480000,
  },
  {
    id: 18,
    eid: 'a1f1c018-1414-4fff-8fff-141414141414',
    name: 'Evelyn Martinez',
    currentlyWorking: 'yes',
    email: 'evelyn.martinez@example.com',
    salary: 860000,
  },
  {
    id: 19,
    eid: 'a1f1c019-1515-4aaa-8aaa-151515151515',
    name: 'Lucas Robinson',
    currentlyWorking: 'yes',
    email: 'lucas.robinson@example.com',
    salary: 800000,
  },
  {
    id: 20,
    eid: 'a1f1c020-1616-4bbb-8bbb-161616161616',
    name: 'Harper Clark',
    currentlyWorking: 'no',
    email: 'harper.clark@example.com',
    salary: 490000,
  },
];

export const BASIC_ATTENDANCE = [
  {
    id: 1,
    clock_in: '09:00:00',
    clock_out: '17:30:00',
    today_in: '2026-01-05',
  },
  {
    id: 2,
    clock_in: '08:45:00',
    clock_out: '16:45:00',
    today_in: '2026-01-05',
  },
  {
    id: 3,
    clock_in: '10:00:00',
    clock_out: '18:00:00',
    today_in: '2026-01-05',
  },
  {
    id: 4,
    clock_in: '09:15:00',
    clock_out: '17:00:00',
    today_in: '2026-01-05',
  },
  {
    id: 5,
    clock_in: '08:30:00',
    clock_out: '17:15:00',
    today_in: '2026-01-05',
  },
];

export const MOCK_FORMDATA: any = {
  name:'gk',
  password:'no',
  state:'ts'
}